### PR TITLE
Missing set of m_connected flag

### LINKED ISSUE #1288: master.68fc436e no work with eth-proxy, whereas v0.15rc2 was fine
0.16.0 not working with `eth-proxy` ...

```
 $ ~/ethminer-0.16.0.dev/ethminer -v 9 --farm-recheck 400 --opencl-device 1 -R -G http://happy.home:8080
m 18:25:27 ethminer ethminer 0.16.0.dev0+commit.68fc436e
 m 18:25:27 ethminer Build: linux/release
 i 18:25:27 ethminer Found suitable OpenCL device [Ellesmere] with 8,583,995,392 bytes of GPU memory
... [repeated 11 times] ...
 i 18:25:27 ethminer Configured pool happy.home:8080
 i 18:25:27 main     Selected pool happy.home:8080
 i 18:25:27 main     Connected to happy.home
 i 18:25:27 main     Spinning up miners...
cl 18:25:27 cl-0     No work. Pause for 3 s.
 i 18:25:28 main     Selected pool happy.home:8080
 i 18:25:28 main     Connected to happy.home
 i 18:25:29 main     Selected pool happy.home:8080
 i 18:25:29 main     Connected to happy.home
cl 18:25:30 cl-0     No work. Pause for 3 s.
```

Whereas 0.15.0rc2 is working with `eth-proxy` ...

```
$ ~/ethminer-0.15rc2/ethminer -v 9 --farm-recheck 400 --opencl-device 1 -R -G http://happy.home:8080
 m 18:25:57 ethminer ethminer 0.15.0rc2
 m 18:25:57 ethminer Build: linux/release
 i 18:25:57 ethminer Found suitable OpenCL device [Ellesmere] with 8583995392 bytes of GPU memory
... [repeated 11 times] ...
 i 18:25:57 main     Selected pool happy.home:8080
 i 18:25:57 getwork  Connected to happy.home
 i 18:25:57 getwork  Spinning up miners...
cl 18:25:57 cl-0     No work. Pause for 3 s.
 i 18:25:57 getwork  Job: #9acb3043… happy.home
 i 18:25:57 getwork  Pool difficulty: 10.00K megahash
 i 18:25:57 getwork  New epoch 194
 i 18:25:58 getwork  Job: #587f6078… happy.home
```

0.15.0rc is a release binary.

I built 0.16.0dev from `master:commit.68fc436e` under Ubuntu 16.04 (kernel 4.15.x HWE) ...
`cmake .. -DETHASHCUDA=OFF`

System is 12 x AMD RX580's with no CUDA devices or software present .

- - -

I tried to get info from `eth-proxy.log`, but `DEBUG=True` only seems to bother with the pool connection and not local incoming get work connections. That is to say, there's nothing in that log at all concerning incoming connections.

If this is not a bug with `ethminer`, then I'd be just as happy for an alternative to `eth-proxy.py` that is known to work, if one exists?

Thanks.

### PR DESCRIPTION
**Pull request by AndreaLanfranchi**
Fixes #1288

Also Clang'ed all file.

### CODE REVIEW

File: libpoolprotocols/getwork/EthGetworkClient.cpp [hunk 1]
```diff
@@ -8,28 +8,31 @@ using namespace std;
...
 EthGetworkClient::~EthGetworkClient()
 {
-	p_client = nullptr;
+    p_client = nullptr;
 }
 
 void EthGetworkClient::connect()
 {
-    std::string uri = "http://" + m_conn->Host() + ":" + to_string(m_conn->Port());
+    stringstream ss;
```
Comment (chfast) [inline libpoolprotocols/getwork/EthGetworkClient.cpp]: Why back to stringstream?

Comment (AndreaLanfranchi) [reply libpoolprotocols/getwork/EthGetworkClient.cpp]: Ouch ... it's likely I was not in sync.
Correcting
