### PR TITLE
decouple local/work group sizes for CUDA and CL

### LINKED ISSUE #627: CL parameters is coupled with CUDA?
I was testing something today with -X and various --cl-local-work 256 --cl-global-work 16384
. Depending on the parameters sometimes the CUDA would get errored out.

  X  19:56:27|cl-3      OpenCL init failed: clEnqueueNDRangeKernel: CL_INVALID_WORK_GROUP_SIZE (-54)
 cl  19:56:27|cl-3      Switch time 5810 ms / 2973559 us
  m  19:56:29|main      Speed  33.55 Mh/s    gpu/0  0.00  gpu/1  0.00  gpu/2  0.00  gpu/3 33.55  [A0+0:R0+0:F0] Time: 00:00
Cuda error in func 'ethash_generate_dag' at line 152 : the launch timed out and was terminated.
Cuda error in func 'ethash_generate_dag' at line 152 : the launch timed out and was terminated.
Cuda error in func 'ethash_generate_dag' at line 152 : the launch timed out and was terminated.

I have an OpenCL error but some how trigger CUDA error seems strange to me.

### PR DESCRIPTION
**Pull request by rushstrike**
without this change while in mixed mode -x then --cl-local-work, --cl-global-work  would also affect CUDA side. should fix #627

### CODE REVIEW

File: ethminer/MinerAux.h [hunk 1]
```diff
@@ -308,7 +308,14 @@ class MinerCLI
 #if ETH_ETHASHCL || ETH_ETHASHCUDA
 		else if ((arg == "--cl-global-work" || arg == "--cuda-grid-size")  && i + 1 < argc)
```
Comment (jean-m-cyr) [inline ethminer/MinerAux.h]: Just split this up into 2 if's. Someone just tried a shortcut here and overloaded a variable with two distinct meanings. You did the right thing creating two separate unrelated control vars. Now handle them in separate ifs.

File: ethminer/MinerAux.h [hunk 2]
```diff
@@ -317,7 +324,14 @@ class MinerCLI
 			}
 		else if ((arg == "--cl-local-work" || arg == "--cuda-block-size") && i + 1 < argc)
 			try {
-				m_localWorkSize = stol(argv[++i]);
+				if (arg == "--cl-local-work")
+				{
+					m_localWorkSize_CL = stol(argv[++i]);
```
Comment (jean-m-cyr) [inline ethminer/MinerAux.h]: Good, 2 separate vars... name them for what they are.. so they kind of match the arg symbol.

ie. m_localWorkSize for CL, and m_blockSize for CUDA.

If you split the outer if, you won't need this inner if.

File: ethminer/MinerAux.h [hunk 3]
```diff
@@ -1077,14 +1091,12 @@ class MinerCLI
 	unsigned m_openclDeviceCount = 0;
 	unsigned m_openclDevices[16];
 	unsigned m_openclThreadsPerHash = 8;
-#if !ETH_ETHASHCUDA
-	unsigned m_globalWorkSizeMultiplier = CLMiner::c_defaultGlobalWorkSizeMultiplier;
-	unsigned m_localWorkSize = CLMiner::c_defaultLocalWorkSize;
-#endif
 #endif
+unsigned m_globalWorkSizeMultiplier_CL = CLMiner::c_defaultGlobalWorkSizeMultiplier;
```
Comment (jean-m-cyr) [inline ethminer/MinerAux.h]: Again, these would make more sense if the names lined up with the constant names.
Something like:

unsigned m_globalGridSize = CUDAMiner::c_defaultGridSize;
